# Generated by Django 5.1.11 on 2025-07-11 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaletteFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
                ('folder_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Palette File Type',
                'verbose_name_plural': 'Palette File Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('primary', models.CharField(max_length=7)),
                ('secondary', models.CharField(blank=True, max_length=7, null=True)),
                ('tertiary', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='palettes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Palette',
                'verbose_name_plural': 'Palettes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaletteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='generator.palette')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.palettefiletype')),
            ],
            options={
                'verbose_name': 'Palette File',
                'verbose_name_plural': 'Palette Files',
                'ordering': ['-updated_at'],
                'unique_together': {('palette', 'file_type')},
            },
        ),
    ]
