# Generated by Django 5.1.11 on 2025-07-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palette',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='palette',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='palette',
            name='storage_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
