# Generated by Django 5.1.11 on 2025-07-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_palette_error_message_palette_is_processing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palettefiletype',
            name='folder_name',
        ),
        migrations.AddField(
            model_name='palettefile',
            name='file_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='palettefiletype',
            name='file_extension',
            field=models.CharField(blank=True, help_text="File extension without the dot, e.g., 'png', 'xlsx'", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='palettefile',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
